steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/usr/sap/scp/mta.jar'
  neoDeploy:
    neoHome: '/usr/sap/scp/neo-java-web-sdk-3.81.16/'
    neo:
      credentialsId: 'HCP_S0001142741'
      account: 's0001142741trial'
      host: 'hanatrial.ondemand.com'